# Generated by Django 5.1 on 2024-08-13 16:59

import django.db.models.deletion
import django_jwt.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JWTToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=1024)),
                ('expires_at', models.DateTimeField()),
                ('type', models.IntegerField(choices=[('ACCESS', 1), ('REFRESH', 2)], default=django_jwt.models.TokenType['ACCESS'])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jwt_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
